services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]